### PR TITLE
Redundant link

### PR DESCRIPTION
**Pull request by deavmi**
Idk, remove it maybe. Or just remove the one right at the top of the `README.md` and use the one I removed in this commit rather.

### CODE REVIEW

**Comment by vesellov** [comment]
Hi deavmi! Nice to meet you. why you would like to remove the link?

**Comment by vesellov** [comment]
oh, really. we have two links in the README. agree!

**Comment by deavmi** [comment]
Nice to meet you too @vesellov . Is this project written in Python If I am correct?

**Comment by deavmi** [comment]
Looks cool. I definately want to use it :)

**Comment by vesellov** [comment]
Thanks. Yes this is only python code. For gui I have some html, js, css also..

**Comment by vesellov** [comment]
feel free to ask any questions, i am happy to chat :-)

**Comment by deavmi** [comment]
Awesome. Will do.

**Comment by deavmi** [comment]
Oh okay. Cooleo. Is there some sort of TC-based API to interact with t 
BitDust node?

**Comment by deavmi** [comment]
- TC = TCP-based

**Comment by vesellov** [comment]
You can use API methods to interact with BitDust instance executed 
locally : http://bitdust.io/api.html

BitDust software use JSON RPC local server to provide interface to 
internal methods, port number is 8083, see 
~/.bitdust/metadata/localjsonrpcport

Say you run "bitdust" in one terminal window (you can see lots of logs 
running) and in another terminal you can run say "bitdust api 
suppliers_list" to execute api method suppliers_list() and get results.

To call method from Python code you can see examples in 
bitdust.devel/interface/jsonrpc_client.py

So you can access bitdust from other application using this API.

**Comment by deavmi** [comment]
Awesome. :)

**Comment by vesellov** [comment]
Tristan. finally got some time to merge the code, so your changes should 
be in the devel repo now.

**Comment by deavmi** [comment]
Cooleo. :)

**Comment by deavmi** [comment]
Thanks :)

**Pull request merged**
